title: practical admin
baseurl: "/blog" 
url: ""

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
