title: practical admin
baseurl: "/blog" 
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-primer

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
